/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateQuizRouteImport } from './routes/create.quiz'
import { Route as GetQuizIdRouteImport } from './routes/get.quiz.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateQuizRoute = CreateQuizRouteImport.update({
  id: '/create/quiz',
  path: '/create/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuizIdRoute = GetQuizIdRouteImport.update({
  id: '/get/quiz/$id',
  path: '/get/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/quiz': typeof CreateQuizRoute
  '/get/quiz/$id': typeof GetQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/quiz': typeof CreateQuizRoute
  '/get/quiz/$id': typeof GetQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/quiz': typeof CreateQuizRoute
  '/get/quiz/$id': typeof GetQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create/quiz' | '/get/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create/quiz' | '/get/quiz/$id'
  id: '__root__' | '/' | '/create/quiz' | '/get/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateQuizRoute: typeof CreateQuizRoute
  GetQuizIdRoute: typeof GetQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/quiz': {
      id: '/create/quiz'
      path: '/create/quiz'
      fullPath: '/create/quiz'
      preLoaderRoute: typeof CreateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get/quiz/$id': {
      id: '/get/quiz/$id'
      path: '/get/quiz/$id'
      fullPath: '/get/quiz/$id'
      preLoaderRoute: typeof GetQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateQuizRoute: CreateQuizRoute,
  GetQuizIdRoute: GetQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
